---
title : "A practical primer on transparent research workflows"
author: "Frederik Aust"
output: pdf_document
---

Psychological science is facing a crisis of confidence fueled by concerns about replicability of empirical findings (e.g., Open Science Collaboration, 2015).
In response, psychologists have been reviewing how they do research and are leading many initiatives to improve replicability.
A fundamental element is greater transparency and intersubjective verifiability:
Researchers increasingly publish research materials, data and analysis scripts, publicly preregister their studies, and share and discuss preprints.
The evolving open science ecosystem provides a variety of tools and services to help researchers adopt transparent research practices.
However, setting up a transparent research workflow involves a plethora of decisions that can be off-putting.
Fortunately, transparent research practices can be adopted piecemeal---each incremental step adds positive value for individual researchers and the credibility of psychological research.
This active workshop will walk participants through the process of preparing and sharing their research products, including materials, data, analysis scripts, and study protocols.
It will address what, when, and how to share and help participants develop transparent, less error-prone, and more reproducible research workflows.


Klein, O., Hardwicke, T. E., Aust, F., Breuer, J., Danielsson, H., Hofelich Mohr, A., IJzerman, H., Nilsonne, G., Vanpaemel, W., & Frank, M. C. (in press). A practical guide for transparency in psychological science. Collabra: Psychology. Retrieved from https://psyarxiv.com/rtygm/
